// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopManagement.Data.Database;

#nullable disable

namespace ShopManagement.Data.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20240906203606_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShopManagement.Data.Models.CustomerDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("be7a13fa-f221-47ae-a5d5-ac0c7fee0287"),
                            BirthDate = new DateTime(1985, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "John Doe",
                            RegistrationDate = new DateTime(2024, 9, 6, 23, 36, 6, 351, DateTimeKind.Local).AddTicks(8670)
                        },
                        new
                        {
                            Id = new Guid("b9288f91-0bcd-4835-a1a0-d366d8acacb5"),
                            BirthDate = new DateTime(1990, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Jane Smith",
                            RegistrationDate = new DateTime(2024, 9, 6, 23, 36, 6, 351, DateTimeKind.Local).AddTicks(8678)
                        },
                        new
                        {
                            Id = new Guid("8b955699-5414-4a79-839c-75abde655ef4"),
                            BirthDate = new DateTime(1975, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bill Johnson",
                            RegistrationDate = new DateTime(2024, 9, 6, 23, 36, 6, 351, DateTimeKind.Local).AddTicks(8680)
                        },
                        new
                        {
                            Id = new Guid("8fc409f4-a743-466b-95a3-553d818ae949"),
                            BirthDate = new DateTime(1995, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Anna Williams",
                            RegistrationDate = new DateTime(2024, 9, 6, 23, 36, 6, 351, DateTimeKind.Local).AddTicks(8681)
                        },
                        new
                        {
                            Id = new Guid("bc9174cb-fdf0-4e6c-be1d-ec71e7c00831"),
                            BirthDate = new DateTime(1980, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "George Brown",
                            RegistrationDate = new DateTime(2024, 9, 6, 23, 36, 6, 351, DateTimeKind.Local).AddTicks(8683)
                        });
                });

            modelBuilder.Entity("ShopManagement.Data.Models.ProductDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b982edb0-6a9f-4d55-9cd8-17849cae91cc"),
                            Category = "Electronics",
                            Name = "Laptop",
                            Price = 1500m,
                            SKU = "LPT123"
                        },
                        new
                        {
                            Id = new Guid("076e214f-d0e6-4390-ba95-cbca4f357bb8"),
                            Category = "Electronics",
                            Name = "Smartphone",
                            Price = 800m,
                            SKU = "SPH456"
                        },
                        new
                        {
                            Id = new Guid("c511d84d-a634-4844-9d12-69fb1f2afc27"),
                            Category = "Electronics",
                            Name = "Tablet",
                            Price = 600m,
                            SKU = "TBL789"
                        },
                        new
                        {
                            Id = new Guid("e614d34a-4391-4f0d-bc85-3bc65bdc3d91"),
                            Category = "Furniture",
                            Name = "Office Chair",
                            Price = 120m,
                            SKU = "CH123"
                        },
                        new
                        {
                            Id = new Guid("baee2f86-ca43-4485-aad0-1fa410905c7e"),
                            Category = "Furniture",
                            Name = "Dining Table",
                            Price = 300m,
                            SKU = "DT456"
                        },
                        new
                        {
                            Id = new Guid("515f2380-8f7f-4a31-8d8d-d2942bf4d51b"),
                            Category = "Sports",
                            Name = "Running Shoes",
                            Price = 80m,
                            SKU = "RS789"
                        },
                        new
                        {
                            Id = new Guid("26e73e23-3208-41b2-a830-8bfcaa96cfd6"),
                            Category = "Sports",
                            Name = "Basketball",
                            Price = 50m,
                            SKU = "BB123"
                        },
                        new
                        {
                            Id = new Guid("f4eb1d6e-608c-4d56-969e-90158560c858"),
                            Category = "KitchenAppliances",
                            Name = "Blender",
                            Price = 90m,
                            SKU = "BL123"
                        },
                        new
                        {
                            Id = new Guid("0c6816a9-f275-48a4-b8a1-15b05b629db5"),
                            Category = "KitchenAppliances",
                            Name = "Microwave",
                            Price = 150m,
                            SKU = "MW456"
                        },
                        new
                        {
                            Id = new Guid("d06af2f1-2ef3-422d-903f-17f3cc1b457a"),
                            Category = "HomeAppliances",
                            Name = "Vacuum Cleaner",
                            Price = 200m,
                            SKU = "VC123"
                        });
                });

            modelBuilder.Entity("ShopManagement.Data.Models.PurchaseDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f27e7e8d-d10e-4560-ad16-7120b62a0ef9"),
                            CustomerId = new Guid("be7a13fa-f221-47ae-a5d5-ac0c7fee0287"),
                            Date = new DateTime(2024, 7, 18, 23, 36, 6, 351, DateTimeKind.Local).AddTicks(8740),
                            Number = "ORD5714",
                            TotalAmount = 400m
                        },
                        new
                        {
                            Id = new Guid("85541de5-7d0c-409a-92bf-d78033473efc"),
                            CustomerId = new Guid("be7a13fa-f221-47ae-a5d5-ac0c7fee0287"),
                            Date = new DateTime(2024, 6, 29, 23, 36, 6, 351, DateTimeKind.Local).AddTicks(8767),
                            Number = "ORD4742",
                            TotalAmount = 1290m
                        },
                        new
                        {
                            Id = new Guid("5b8a66de-3131-4619-adec-06fd4351c7e6"),
                            CustomerId = new Guid("b9288f91-0bcd-4835-a1a0-d366d8acacb5"),
                            Date = new DateTime(2024, 6, 11, 23, 36, 6, 351, DateTimeKind.Local).AddTicks(8776),
                            Number = "ORD3049",
                            TotalAmount = 6690m
                        },
                        new
                        {
                            Id = new Guid("9f04d3f7-44a5-478d-b51f-a673f926c4ca"),
                            CustomerId = new Guid("8b955699-5414-4a79-839c-75abde655ef4"),
                            Date = new DateTime(2024, 6, 26, 23, 36, 6, 351, DateTimeKind.Local).AddTicks(8825),
                            Number = "ORD3605",
                            TotalAmount = 3200m
                        },
                        new
                        {
                            Id = new Guid("8f6715f6-f377-413c-93ce-a5f15cee4576"),
                            CustomerId = new Guid("8b955699-5414-4a79-839c-75abde655ef4"),
                            Date = new DateTime(2024, 7, 11, 23, 36, 6, 351, DateTimeKind.Local).AddTicks(8832),
                            Number = "ORD6078",
                            TotalAmount = 1260m
                        },
                        new
                        {
                            Id = new Guid("121bb3b9-4f9d-42c4-ac97-1b67c754c537"),
                            CustomerId = new Guid("8b955699-5414-4a79-839c-75abde655ef4"),
                            Date = new DateTime(2024, 8, 5, 23, 36, 6, 351, DateTimeKind.Local).AddTicks(8841),
                            Number = "ORD3114",
                            TotalAmount = 3100m
                        },
                        new
                        {
                            Id = new Guid("18e5e266-7b83-4ace-abf3-933443ccbe38"),
                            CustomerId = new Guid("8fc409f4-a743-466b-95a3-553d818ae949"),
                            Date = new DateTime(2024, 6, 29, 23, 36, 6, 351, DateTimeKind.Local).AddTicks(8849),
                            Number = "ORD1978",
                            TotalAmount = 900m
                        },
                        new
                        {
                            Id = new Guid("faa790fe-059d-4b97-947c-9d0165817678"),
                            CustomerId = new Guid("8fc409f4-a743-466b-95a3-553d818ae949"),
                            Date = new DateTime(2024, 8, 11, 23, 36, 6, 351, DateTimeKind.Local).AddTicks(8859),
                            Number = "ORD6987",
                            TotalAmount = 320m
                        },
                        new
                        {
                            Id = new Guid("eac094d5-67a5-49e3-815e-7c36fd87c4cd"),
                            CustomerId = new Guid("bc9174cb-fdf0-4e6c-be1d-ec71e7c00831"),
                            Date = new DateTime(2024, 8, 22, 23, 36, 6, 351, DateTimeKind.Local).AddTicks(8864),
                            Number = "ORD1990",
                            TotalAmount = 4000m
                        },
                        new
                        {
                            Id = new Guid("02b432ac-ff22-4ce3-aba5-535e3d34851f"),
                            CustomerId = new Guid("bc9174cb-fdf0-4e6c-be1d-ec71e7c00831"),
                            Date = new DateTime(2024, 7, 8, 23, 36, 6, 351, DateTimeKind.Local).AddTicks(8871),
                            Number = "ORD2291",
                            TotalAmount = 2400m
                        });
                });

            modelBuilder.Entity("ShopManagement.Data.Models.PurchaseItemDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ecc296fb-7a57-47df-9b9c-e22197d8395b"),
                            ProductId = new Guid("e614d34a-4391-4f0d-bc85-3bc65bdc3d91"),
                            PurchaseId = new Guid("f27e7e8d-d10e-4560-ad16-7120b62a0ef9"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("0889c5da-a529-4161-939f-798db4ebca64"),
                            ProductId = new Guid("26e73e23-3208-41b2-a830-8bfcaa96cfd6"),
                            PurchaseId = new Guid("f27e7e8d-d10e-4560-ad16-7120b62a0ef9"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("f01792d3-691f-4c50-8281-38a48a23c413"),
                            ProductId = new Guid("f4eb1d6e-608c-4d56-969e-90158560c858"),
                            PurchaseId = new Guid("f27e7e8d-d10e-4560-ad16-7120b62a0ef9"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("cd0b3239-7020-40d6-b18b-bb6e28a2f46e"),
                            ProductId = new Guid("baee2f86-ca43-4485-aad0-1fa410905c7e"),
                            PurchaseId = new Guid("85541de5-7d0c-409a-92bf-d78033473efc"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("52fa920b-c75f-42fe-95de-d14f5728aa75"),
                            ProductId = new Guid("f4eb1d6e-608c-4d56-969e-90158560c858"),
                            PurchaseId = new Guid("85541de5-7d0c-409a-92bf-d78033473efc"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("c2d85958-e428-4e1a-ae95-8a182cdc3f4d"),
                            ProductId = new Guid("e614d34a-4391-4f0d-bc85-3bc65bdc3d91"),
                            PurchaseId = new Guid("5b8a66de-3131-4619-adec-06fd4351c7e6"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("7ef393f2-e5e2-49e6-b7bc-6cbc6b269483"),
                            ProductId = new Guid("0c6816a9-f275-48a4-b8a1-15b05b629db5"),
                            PurchaseId = new Guid("5b8a66de-3131-4619-adec-06fd4351c7e6"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("f5826f1b-3ce3-4f40-b4af-90d9a8ab90c2"),
                            ProductId = new Guid("b982edb0-6a9f-4d55-9cd8-17849cae91cc"),
                            PurchaseId = new Guid("5b8a66de-3131-4619-adec-06fd4351c7e6"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("bb575500-0fad-4a72-bc1f-545d09710c40"),
                            ProductId = new Guid("b982edb0-6a9f-4d55-9cd8-17849cae91cc"),
                            PurchaseId = new Guid("9f04d3f7-44a5-478d-b51f-a673f926c4ca"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("87a87833-beb8-4279-a303-41715455465b"),
                            ProductId = new Guid("d06af2f1-2ef3-422d-903f-17f3cc1b457a"),
                            PurchaseId = new Guid("9f04d3f7-44a5-478d-b51f-a673f926c4ca"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("e21896d1-d36c-41e6-912b-d413b4c920b5"),
                            ProductId = new Guid("f4eb1d6e-608c-4d56-969e-90158560c858"),
                            PurchaseId = new Guid("8f6715f6-f377-413c-93ce-a5f15cee4576"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("02ceb7d8-fd09-410a-82ff-c8c0e43ba5d5"),
                            ProductId = new Guid("baee2f86-ca43-4485-aad0-1fa410905c7e"),
                            PurchaseId = new Guid("8f6715f6-f377-413c-93ce-a5f15cee4576"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("46d4ffe9-8afa-4434-a0e0-cff05e42ec3e"),
                            ProductId = new Guid("c511d84d-a634-4844-9d12-69fb1f2afc27"),
                            PurchaseId = new Guid("121bb3b9-4f9d-42c4-ac97-1b67c754c537"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("90008a03-f2de-4425-8d93-d0152be7675e"),
                            ProductId = new Guid("076e214f-d0e6-4390-ba95-cbca4f357bb8"),
                            PurchaseId = new Guid("121bb3b9-4f9d-42c4-ac97-1b67c754c537"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("3c4220ac-b9f3-41f8-854f-cd5a10d132ed"),
                            ProductId = new Guid("0c6816a9-f275-48a4-b8a1-15b05b629db5"),
                            PurchaseId = new Guid("121bb3b9-4f9d-42c4-ac97-1b67c754c537"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("7abfe1bf-a8d8-463c-adba-534dd15059bf"),
                            ProductId = new Guid("baee2f86-ca43-4485-aad0-1fa410905c7e"),
                            PurchaseId = new Guid("18e5e266-7b83-4ace-abf3-933443ccbe38"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("2ee8a6ff-a994-4621-bd81-6f5fa32b97ac"),
                            ProductId = new Guid("f4eb1d6e-608c-4d56-969e-90158560c858"),
                            PurchaseId = new Guid("18e5e266-7b83-4ace-abf3-933443ccbe38"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("7bca26cf-4a07-4233-a971-df3650c22643"),
                            ProductId = new Guid("e614d34a-4391-4f0d-bc85-3bc65bdc3d91"),
                            PurchaseId = new Guid("18e5e266-7b83-4ace-abf3-933443ccbe38"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("6f70c8d1-03c4-4ea0-83a4-c54cead0e747"),
                            ProductId = new Guid("515f2380-8f7f-4a31-8d8d-d2942bf4d51b"),
                            PurchaseId = new Guid("faa790fe-059d-4b97-947c-9d0165817678"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("6f9fdb48-d8b0-47ee-8d71-f2ad7d391f4f"),
                            ProductId = new Guid("076e214f-d0e6-4390-ba95-cbca4f357bb8"),
                            PurchaseId = new Guid("eac094d5-67a5-49e3-815e-7c36fd87c4cd"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("6e9e3c03-d9c9-48bc-a8dd-d23150784a01"),
                            ProductId = new Guid("d06af2f1-2ef3-422d-903f-17f3cc1b457a"),
                            PurchaseId = new Guid("eac094d5-67a5-49e3-815e-7c36fd87c4cd"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("dd425354-2d99-4cb6-9be5-8b2dd9f5816e"),
                            ProductId = new Guid("076e214f-d0e6-4390-ba95-cbca4f357bb8"),
                            PurchaseId = new Guid("02b432ac-ff22-4ce3-aba5-535e3d34851f"),
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("ShopManagement.Data.Models.PurchaseDb", b =>
                {
                    b.HasOne("ShopManagement.Data.Models.CustomerDb", "Customer")
                        .WithMany("Purchases")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ShopManagement.Data.Models.PurchaseItemDb", b =>
                {
                    b.HasOne("ShopManagement.Data.Models.ProductDb", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopManagement.Data.Models.PurchaseDb", "Purchase")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("ShopManagement.Data.Models.CustomerDb", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("ShopManagement.Data.Models.PurchaseDb", b =>
                {
                    b.Navigation("PurchaseItems");
                });
#pragma warning restore 612, 618
        }
    }
}
